kind: Service
apiVersion: v1
metadata:
  name: carts
spec:
  type: ClusterIP
  selector:
    app: carts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    app: carts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
      - name: carts
        image: sudheshpn/carts:latest
        ports:
        - containerPort: 8080
